### ISSUE TITLE
window system does not support

### ISSUE THREAD

**Issue by yangyongguan** [latticexyz/emojimon#11]
There is a problem with auto-generated code path under window system
<img width="688" alt="081b6cc2b9f92b2971f3d4f41795020" src="https://github.com/latticexyz/emojimon/assets/13481577/c11d585c-908b-4fb2-9f9b-d104a8189dd0">

**Comment by alvrs** [comment]
can be fixed by upgrading to latest MUD alpha (alpha-1.173)
