### ISSUE TITLE
bug: Many unknown white squares appear

### ISSUE THREAD

**Issue by babytdream** [latticexyz/emojimon#23]
I can move the emoji.
![image](https://github.com/latticexyz/emojimon/assets/74184102/d53f72f2-9982-43ff-a718-e7c4126428f9)

**Comment by frolic** [comment]
seems like maybe your OS font is missing 🪨 (rock emoji)?

**Comment by frolic** [comment]
(closing this as won't fix, feel free to customize your own emojimon's emojis)
